### ISSUE TITLE
Slowdown caused by mlang.dll!CMLFLink2::GetFontCodePages

### ISSUE THREAD

**Issue by TruePikachu** [DavidKinder/Windows-Glk#9]
Tested under both Glulxe and Git, both using Glk.dll with file version 0.7.5.50, and tested under multiple stories (first noticed with _The Wizard Sniffer_ but reverified with _Counterfeit Monkey_), there's a noticable delay when issuing a command to the story (e.g. more than half a second under _Wizard Sniffer_). Running an ETW trace to locate the issue indicates massive CPU usage on the function `CMLFLink2::GetFontCodePages` (from `mlang.dll`) and its callees. This appears in the root element for the process's main thread under WPA, so I'm not 100% sure if it's from Glk or other common code between Glulxe and Git; regardless, neither of those processes should be dealing with the system's font interfaces _directly_, so I'm inclined to believe it's a Glk issue.

EDIT: I just tested _Wizard Sniffer_ under Gargoyle Git; the issue does _not_ arise there, which makes me pretty certain it's in Glk.

**Comment by DavidKinder** [comment]
Windows Glk does use mlang.dll, which is a part of Windows that provides support for font linking, so that if a game uses a glyph not in the current font, some other font is used instead. I definitely don't see heavy CPU use for calls to GetFontCodePages(). Do you have a lot of large fonts installed in your system?

**Comment by DavidKinder** [comment]
Cannot reproduce, and no response from original reporter.
